"""Initial NJURA schema

Revision ID: 4ba936e52454
Revises: 
Create Date: 2026-07-06 14:40:41.515716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ba936e52454'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('company_code', sa.String(length=20), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('initials', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('alternative_phone', sa.String(length=20), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('contact_person', sa.String(length=150), nullable=True),
    sa.Column('contact_person_phone', sa.String(length=20), nullable=True),
    sa.Column('contact_person_email', sa.String(length=120), nullable=True),
    sa.Column('registration_number', sa.String(length=50), nullable=True),
    sa.Column('kra_pin', sa.String(length=20), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('brand_primary_color', sa.String(length=20), nullable=True),
    sa.Column('brand_secondary_color', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('town', sa.String(length=100), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('postal_address', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('date_format', sa.String(length=20), nullable=False),
    sa.Column('allow_outlet_creation', sa.Boolean(), nullable=False),
    sa.Column('allow_order_editing', sa.Boolean(), nullable=False),
    sa.Column('require_visit_before_order', sa.Boolean(), nullable=False),
    sa.Column('company_status', sa.Enum('Pending', 'Active', 'Suspended', 'Archived', name='company_status_enum'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kra_pin'),
    sa.UniqueConstraint('registration_number')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_company_code'), ['company_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_companies_company_status'), ['company_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_companies_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_companies_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_companies_uuid'), ['uuid'], unique=True)

    op.create_table('permissions',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('is_system_permission', sa.Boolean(), nullable=False),
    sa.Column('permission_status', sa.Enum('Active', 'Inactive', name='permission_status_enum'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_module'), ['module'], unique=False)
        batch_op.create_index(batch_op.f('ix_permissions_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_permissions_permission_status'), ['permission_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_permissions_uuid'), ['uuid'], unique=True)

    op.create_table('roles',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system_role', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('role_status', sa.Enum('Active', 'Inactive', name='role_status_enum'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_roles_role_status'), ['role_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_roles_uuid'), ['uuid'], unique=True)

    op.create_table('outlet_categories',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_status', sa.Enum('Active', 'Inactive', name='outlet_category_status_enum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_company_outlet_category_name')
    )
    with op.batch_alter_table('outlet_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outlet_categories_category_status'), ['category_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_outlet_categories_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outlet_categories_uuid'), ['uuid'], unique=True)

    op.create_table('product_categories',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category_code', sa.String(length=30), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_status', sa.Enum('Active', 'Inactive', name='product_category_status_enum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_company_product_category_name')
    )
    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_categories_category_status'), ['category_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_categories_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_categories_uuid'), ['uuid'], unique=True)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('is_allowed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_permissions_permission_id'), ['permission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_permissions_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_permissions_uuid'), ['uuid'], unique=True)

    op.create_table('subscriptions',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(length=50), nullable=False),
    sa.Column('billing_cycle', sa.Enum('Monthly', 'Quarterly', 'Bi-Annual', 'Annual', name='subscription_billing_cycle'), nullable=False),
    sa.Column('status', sa.Enum('Trial', 'Active', 'Expired', 'Grace Period', 'Suspended', 'Cancelled', name='subscription_status'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('trial_end_date', sa.Date(), nullable=True),
    sa.Column('grace_period_end', sa.Date(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('last_payment_date', sa.DateTime(), nullable=True),
    sa.Column('next_billing_date', sa.Date(), nullable=True),
    sa.Column('payment_reference', sa.String(length=150), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('max_fsrs', sa.Integer(), nullable=False),
    sa.Column('max_products', sa.Integer(), nullable=False),
    sa.Column('max_outlets', sa.Integer(), nullable=False),
    sa.Column('max_distributors', sa.Integer(), nullable=False),
    sa.Column('gps_tracking', sa.Boolean(), nullable=False),
    sa.Column('analytics_enabled', sa.Boolean(), nullable=False),
    sa.Column('api_access', sa.Boolean(), nullable=False),
    sa.Column('offline_mode', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_uuid'), ['uuid'], unique=True)

    op.create_table('territories',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('sub_county', sa.String(length=100), nullable=True),
    sa.Column('ward', sa.String(length=100), nullable=True),
    sa.Column('town', sa.String(length=100), nullable=True),
    sa.Column('territory_status', sa.Enum('Active', 'Inactive', name='territory_status_enum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_company_territory_code'),
    sa.UniqueConstraint('company_id', 'name', name='uq_company_territory_name')
    )
    with op.batch_alter_table('territories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_territories_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_territories_territory_status'), ['territory_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_territories_uuid'), ['uuid'], unique=True)

    op.create_table('users',
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('profile_photo', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=50), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('force_password_change', sa.Boolean(), nullable=False),
    sa.Column('account_status', sa.Enum('Pending', 'Active', 'Suspended', 'Locked', 'Archived', name='user_account_status_enum'), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=False),
    sa.Column('preferred_language', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'username', name='uq_company_username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_account_status'), ['account_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_uuid'), ['uuid'], unique=True)

    op.create_table('audit_logs',
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_method', sa.String(length=10), nullable=True),
    sa.Column('request_url', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('Success', 'Failed', 'Warning', name='audit_log_status_enum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_module'), ['module'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_uuid'), ['uuid'], unique=True)

    op.create_table('dashboards',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dashboard_name', sa.String(length=100), nullable=False),
    sa.Column('dashboard_type', sa.Enum('Super Admin', 'Company Admin', 'Distributor', 'FSR', name='dashboard_type_enum'), nullable=False),
    sa.Column('layout', sa.JSON(), nullable=True),
    sa.Column('widgets', sa.JSON(), nullable=True),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('default_dashboard', sa.Boolean(), nullable=False),
    sa.Column('auto_refresh', sa.Boolean(), nullable=False),
    sa.Column('refresh_interval', sa.Integer(), nullable=False),
    sa.Column('dashboard_status', sa.Enum('Active', 'Inactive', name='dashboard_status_enum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'user_id', name='uq_company_dashboard_user')
    )
    with op.batch_alter_table('dashboards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dashboards_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dashboards_dashboard_status'), ['dashboard_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_dashboards_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dashboards_uuid'), ['uuid'], unique=True)

    op.create_table('distributors',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('territory_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('distributor_code', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('kra_pin', sa.String(length=20), nullable=True),
    sa.Column('registration_number', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('alternative_phone', sa.String(length=20), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('contact_person', sa.String(length=150), nullable=True),
    sa.Column('contact_person_phone', sa.String(length=20), nullable=True),
    sa.Column('contact_person_email', sa.String(length=120), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('town', sa.String(length=100), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('postal_address', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('distributor_status', sa.Enum('Active', 'Inactive', 'Suspended', name='distributor_status_enum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['territory_id'], ['territories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'distributor_code', name='uq_company_distributor_code'),
    sa.UniqueConstraint('company_id', 'name', name='uq_company_distributor_name')
    )
    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_distributors_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_distributors_distributor_status'), ['distributor_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_distributors_territory_id'), ['territory_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_distributors_uuid'), ['uuid'], unique=True)

    op.create_table('notifications',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.Enum('System', 'Order', 'Delivery', 'Visit', 'Product', 'Reminder', 'Announcement', 'Warning', 'Success', name='notification_type_enum'), nullable=False),
    sa.Column('delivery_channel', sa.Enum('In-App', 'Email', 'SMS', 'Push', name='notification_channel_enum'), nullable=False),
    sa.Column('notification_status', sa.Enum('Pending', 'Sent', 'Delivered', 'Read', 'Failed', name='notification_status_enum'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('action_url', sa.String(length=255), nullable=True),
    sa.Column('reference_type', sa.String(length=100), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_notification_status'), ['notification_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_notification_type'), ['notification_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_uuid'), ['uuid'], unique=True)

    op.create_table('products',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('product_category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('product_code', sa.String(length=30), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=50), nullable=False),
    sa.Column('pack_size', sa.String(length=100), nullable=True),
    sa.Column('weight', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('minimum_order_quantity', sa.Integer(), nullable=False),
    sa.Column('reorder_level', sa.Integer(), nullable=True),
    sa.Column('tax_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('product_status', sa.Enum('Active', 'Inactive', 'Discontinued', name='product_status_enum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['product_category_id'], ['product_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'product_code', name='uq_company_product_code'),
    sa.UniqueConstraint('company_id', 'sku', name='uq_company_product_sku')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_product_category_id'), ['product_category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_product_status'), ['product_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_uuid'), ['uuid'], unique=True)

    op.create_table('routes',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('territory_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('route_code', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('visit_frequency', sa.Enum('Daily', 'Weekly', 'Bi-Weekly', 'Monthly', name='route_visit_frequency_enum'), nullable=False),
    sa.Column('visit_day', sa.Enum('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday', name='route_visit_day_enum'), nullable=True),
    sa.Column('estimated_outlets', sa.Integer(), nullable=False),
    sa.Column('estimated_visit_time', sa.Integer(), nullable=True),
    sa.Column('route_status', sa.Enum('Active', 'Inactive', name='route_status_enum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['territory_id'], ['territories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_company_route_name'),
    sa.UniqueConstraint('company_id', 'route_code', name='uq_company_route_code')
    )
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_routes_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_routes_route_status'), ['route_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_routes_territory_id'), ['territory_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_routes_uuid'), ['uuid'], unique=True)

    op.create_table('distributor_users',
    sa.Column('distributor_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('is_primary_contact', sa.Boolean(), nullable=False),
    sa.Column('assigned_date', sa.Date(), nullable=False),
    sa.Column('assignment_status', sa.Enum('Active', 'Inactive', name='distributor_user_status_enum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributors.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('distributor_id', 'user_id', name='uq_distributor_user')
    )
    with op.batch_alter_table('distributor_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_distributor_users_assignment_status'), ['assignment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_distributor_users_distributor_id'), ['distributor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_distributor_users_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_distributor_users_uuid'), ['uuid'], unique=True)

    op.create_table('fsrs',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('distributor_id', sa.Integer(), nullable=False),
    sa.Column('territory_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('employee_number', sa.String(length=30), nullable=False),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('date_employed', sa.Date(), nullable=True),
    sa.Column('employment_type', sa.Enum('Permanent', 'Contract', 'Temporary', 'Intern', name='employment_type_enum'), nullable=False),
    sa.Column('supervisor', sa.String(length=150), nullable=True),
    sa.Column('device_id', sa.String(length=150), nullable=True),
    sa.Column('daily_visit_target', sa.Integer(), nullable=False),
    sa.Column('daily_order_target', sa.Integer(), nullable=False),
    sa.Column('monthly_sales_target', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('gps_tracking_enabled', sa.Boolean(), nullable=False),
    sa.Column('fsr_status', sa.Enum('Active', 'Inactive', 'Suspended', 'On Leave', name='fsr_status_enum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributors.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['territory_id'], ['territories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'employee_number', name='uq_company_employee_number')
    )
    with op.batch_alter_table('fsrs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fsrs_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fsrs_distributor_id'), ['distributor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fsrs_fsr_status'), ['fsr_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_fsrs_route_id'), ['route_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fsrs_territory_id'), ['territory_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fsrs_user_id'), ['user_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_fsrs_uuid'), ['uuid'], unique=True)

    op.create_table('product_prices',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('minimum_selling_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('maximum_selling_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('price_status', sa.Enum('Active', 'Expired', 'Scheduled', name='product_price_status_enum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_prices_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_prices_price_status'), ['price_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_prices_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_prices_uuid'), ['uuid'], unique=True)

    op.create_table('outlets',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('outlet_category_id', sa.Integer(), nullable=False),
    sa.Column('territory_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('distributor_id', sa.Integer(), nullable=False),
    sa.Column('fsr_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('outlet_code', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_name', sa.String(length=150), nullable=True),
    sa.Column('owner_phone', sa.String(length=20), nullable=True),
    sa.Column('owner_email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('alternative_phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('town', sa.String(length=100), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('landmark', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('business_since', sa.Date(), nullable=True),
    sa.Column('average_monthly_sales', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('opening_balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('preferred_visit_day', sa.Enum('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday', name='preferred_visit_day_enum'), nullable=True),
    sa.Column('last_visit_date', sa.Date(), nullable=True),
    sa.Column('last_order_date', sa.Date(), nullable=True),
    sa.Column('outlet_status', sa.Enum('Active', 'Inactive', 'Closed', name='outlet_status_enum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributors.id'], ),
    sa.ForeignKeyConstraint(['fsr_id'], ['fsrs.id'], ),
    sa.ForeignKeyConstraint(['outlet_category_id'], ['outlet_categories.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['territory_id'], ['territories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'outlet_code', name='uq_company_outlet_code')
    )
    with op.batch_alter_table('outlets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outlets_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outlets_distributor_id'), ['distributor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outlets_fsr_id'), ['fsr_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outlets_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_outlets_outlet_category_id'), ['outlet_category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outlets_outlet_status'), ['outlet_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_outlets_route_id'), ['route_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outlets_territory_id'), ['territory_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outlets_uuid'), ['uuid'], unique=True)

    op.create_table('visits',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('outlet_id', sa.Integer(), nullable=False),
    sa.Column('fsr_id', sa.Integer(), nullable=False),
    sa.Column('distributor_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('check_in_time', sa.DateTime(), nullable=False),
    sa.Column('check_out_time', sa.DateTime(), nullable=True),
    sa.Column('visit_duration', sa.Integer(), nullable=True),
    sa.Column('check_in_latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('check_in_longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('check_out_latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('check_out_longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('visit_outcome', sa.Enum('Successful', 'Order Placed', 'Outlet Closed', 'Owner Absent', 'No Stock Required', 'Follow Up Required', 'Survey', name='visit_outcome_enum'), nullable=False),
    sa.Column('customer_feedback', sa.Text(), nullable=True),
    sa.Column('competitor_activity', sa.Text(), nullable=True),
    sa.Column('stock_observation', sa.Text(), nullable=True),
    sa.Column('visit_status', sa.Enum('Open', 'Completed', 'Cancelled', name='visit_status_enum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributors.id'], ),
    sa.ForeignKeyConstraint(['fsr_id'], ['fsrs.id'], ),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visits_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_distributor_id'), ['distributor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_fsr_id'), ['fsr_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_outlet_id'), ['outlet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_route_id'), ['route_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_uuid'), ['uuid'], unique=True)
        batch_op.create_index(batch_op.f('ix_visits_visit_date'), ['visit_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_visit_outcome'), ['visit_outcome'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_visit_status'), ['visit_status'], unique=False)

    op.create_table('orders',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('outlet_id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('distributor_id', sa.Integer(), nullable=False),
    sa.Column('fsr_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('requested_delivery_date', sa.Date(), nullable=True),
    sa.Column('order_type', sa.Enum('Sale', 'Replacement', 'Return', 'Sample', name='order_type_enum'), nullable=False),
    sa.Column('order_source', sa.Enum('Mobile', 'Web', 'API', name='order_source_enum'), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_status', sa.Enum('Pending', 'Partially Paid', 'Paid', name='payment_status_enum'), nullable=False),
    sa.Column('approval_status', sa.Enum('Pending', 'Approved', 'Rejected', name='approval_status_enum'), nullable=False),
    sa.Column('order_status', sa.Enum('Draft', 'Submitted', 'Processing', 'Ready for Dispatch', 'Dispatched', 'Delivered', 'Cancelled', name='order_status_enum'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributors.id'], ),
    sa.ForeignKeyConstraint(['fsr_id'], ['fsrs.id'], ),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'order_number', name='uq_company_order_number')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_approval_status'), ['approval_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_distributor_id'), ['distributor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_fsr_id'), ['fsr_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_order_status'), ['order_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_outlet_id'), ['outlet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_payment_status'), ['payment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_route_id'), ['route_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_uuid'), ['uuid'], unique=True)
        batch_op.create_index(batch_op.f('ix_orders_visit_id'), ['visit_id'], unique=False)

    op.create_table('visit_notes',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('fsr_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('note_type', sa.Enum('General', 'Customer Feedback', 'Competitor Activity', 'Product Display', 'Promotion', 'Stock Observation', 'Follow Up', 'Complaint', 'Other', name='visit_note_type_enum'), nullable=False),
    sa.Column('requires_follow_up', sa.Boolean(), nullable=False),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('note_status', sa.Enum('Open', 'Closed', name='visit_note_status_enum'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['fsr_id'], ['fsrs.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visit_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visit_notes_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visit_notes_fsr_id'), ['fsr_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visit_notes_note_status'), ['note_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_visit_notes_note_type'), ['note_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_visit_notes_uuid'), ['uuid'], unique=True)
        batch_op.create_index(batch_op.f('ix_visit_notes_visit_id'), ['visit_id'], unique=False)

    op.create_table('deliveries',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('distributor_id', sa.Integer(), nullable=False),
    sa.Column('outlet_id', sa.Integer(), nullable=False),
    sa.Column('fsr_id', sa.Integer(), nullable=False),
    sa.Column('delivery_number', sa.String(length=50), nullable=False),
    sa.Column('dispatch_date', sa.DateTime(), nullable=True),
    sa.Column('expected_delivery_date', sa.Date(), nullable=True),
    sa.Column('delivered_date', sa.DateTime(), nullable=True),
    sa.Column('delivered_to', sa.String(length=150), nullable=True),
    sa.Column('recipient_phone', sa.String(length=20), nullable=True),
    sa.Column('delivery_status', sa.Enum('Pending', 'Preparing', 'Dispatched', 'In Transit', 'Delivered', 'Partially Delivered', 'Failed', 'Returned', 'Cancelled', name='delivery_status_enum'), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('customer_comments', sa.Text(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('proof_of_delivery', sa.String(length=255), nullable=True),
    sa.Column('recipient_signature', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributors.id'], ),
    sa.ForeignKeyConstraint(['fsr_id'], ['fsrs.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'delivery_number', name='uq_company_delivery_number')
    )
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deliveries_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliveries_delivery_status'), ['delivery_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliveries_distributor_id'), ['distributor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliveries_fsr_id'), ['fsr_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliveries_order_id'), ['order_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_deliveries_outlet_id'), ['outlet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliveries_uuid'), ['uuid'], unique=True)

    op.create_table('order_items',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_price_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=150), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('free_quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('item_status', sa.Enum('Pending', 'Approved', 'Rejected', 'Cancelled', name='order_item_status_enum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['product_price_id'], ['product_prices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_items_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_item_status'), ['item_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_product_price_id'), ['product_price_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_uuid'), ['uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_items_uuid'))
        batch_op.drop_index(batch_op.f('ix_order_items_product_price_id'))
        batch_op.drop_index(batch_op.f('ix_order_items_product_id'))
        batch_op.drop_index(batch_op.f('ix_order_items_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_items_item_status'))
        batch_op.drop_index(batch_op.f('ix_order_items_company_id'))

    op.drop_table('order_items')
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deliveries_uuid'))
        batch_op.drop_index(batch_op.f('ix_deliveries_outlet_id'))
        batch_op.drop_index(batch_op.f('ix_deliveries_order_id'))
        batch_op.drop_index(batch_op.f('ix_deliveries_fsr_id'))
        batch_op.drop_index(batch_op.f('ix_deliveries_distributor_id'))
        batch_op.drop_index(batch_op.f('ix_deliveries_delivery_status'))
        batch_op.drop_index(batch_op.f('ix_deliveries_company_id'))

    op.drop_table('deliveries')
    with op.batch_alter_table('visit_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visit_notes_visit_id'))
        batch_op.drop_index(batch_op.f('ix_visit_notes_uuid'))
        batch_op.drop_index(batch_op.f('ix_visit_notes_note_type'))
        batch_op.drop_index(batch_op.f('ix_visit_notes_note_status'))
        batch_op.drop_index(batch_op.f('ix_visit_notes_fsr_id'))
        batch_op.drop_index(batch_op.f('ix_visit_notes_company_id'))

    op.drop_table('visit_notes')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_visit_id'))
        batch_op.drop_index(batch_op.f('ix_orders_uuid'))
        batch_op.drop_index(batch_op.f('ix_orders_route_id'))
        batch_op.drop_index(batch_op.f('ix_orders_payment_status'))
        batch_op.drop_index(batch_op.f('ix_orders_outlet_id'))
        batch_op.drop_index(batch_op.f('ix_orders_order_status'))
        batch_op.drop_index(batch_op.f('ix_orders_fsr_id'))
        batch_op.drop_index(batch_op.f('ix_orders_distributor_id'))
        batch_op.drop_index(batch_op.f('ix_orders_company_id'))
        batch_op.drop_index(batch_op.f('ix_orders_approval_status'))

    op.drop_table('orders')
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visits_visit_status'))
        batch_op.drop_index(batch_op.f('ix_visits_visit_outcome'))
        batch_op.drop_index(batch_op.f('ix_visits_visit_date'))
        batch_op.drop_index(batch_op.f('ix_visits_uuid'))
        batch_op.drop_index(batch_op.f('ix_visits_route_id'))
        batch_op.drop_index(batch_op.f('ix_visits_outlet_id'))
        batch_op.drop_index(batch_op.f('ix_visits_fsr_id'))
        batch_op.drop_index(batch_op.f('ix_visits_distributor_id'))
        batch_op.drop_index(batch_op.f('ix_visits_company_id'))

    op.drop_table('visits')
    with op.batch_alter_table('outlets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outlets_uuid'))
        batch_op.drop_index(batch_op.f('ix_outlets_territory_id'))
        batch_op.drop_index(batch_op.f('ix_outlets_route_id'))
        batch_op.drop_index(batch_op.f('ix_outlets_outlet_status'))
        batch_op.drop_index(batch_op.f('ix_outlets_outlet_category_id'))
        batch_op.drop_index(batch_op.f('ix_outlets_name'))
        batch_op.drop_index(batch_op.f('ix_outlets_fsr_id'))
        batch_op.drop_index(batch_op.f('ix_outlets_distributor_id'))
        batch_op.drop_index(batch_op.f('ix_outlets_company_id'))

    op.drop_table('outlets')
    with op.batch_alter_table('product_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_prices_uuid'))
        batch_op.drop_index(batch_op.f('ix_product_prices_product_id'))
        batch_op.drop_index(batch_op.f('ix_product_prices_price_status'))
        batch_op.drop_index(batch_op.f('ix_product_prices_company_id'))

    op.drop_table('product_prices')
    with op.batch_alter_table('fsrs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fsrs_uuid'))
        batch_op.drop_index(batch_op.f('ix_fsrs_user_id'))
        batch_op.drop_index(batch_op.f('ix_fsrs_territory_id'))
        batch_op.drop_index(batch_op.f('ix_fsrs_route_id'))
        batch_op.drop_index(batch_op.f('ix_fsrs_fsr_status'))
        batch_op.drop_index(batch_op.f('ix_fsrs_distributor_id'))
        batch_op.drop_index(batch_op.f('ix_fsrs_company_id'))

    op.drop_table('fsrs')
    with op.batch_alter_table('distributor_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_distributor_users_uuid'))
        batch_op.drop_index(batch_op.f('ix_distributor_users_user_id'))
        batch_op.drop_index(batch_op.f('ix_distributor_users_distributor_id'))
        batch_op.drop_index(batch_op.f('ix_distributor_users_assignment_status'))

    op.drop_table('distributor_users')
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routes_uuid'))
        batch_op.drop_index(batch_op.f('ix_routes_territory_id'))
        batch_op.drop_index(batch_op.f('ix_routes_route_status'))
        batch_op.drop_index(batch_op.f('ix_routes_company_id'))

    op.drop_table('routes')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_uuid'))
        batch_op.drop_index(batch_op.f('ix_products_product_status'))
        batch_op.drop_index(batch_op.f('ix_products_product_category_id'))
        batch_op.drop_index(batch_op.f('ix_products_name'))
        batch_op.drop_index(batch_op.f('ix_products_company_id'))

    op.drop_table('products')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_uuid'))
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_notification_type'))
        batch_op.drop_index(batch_op.f('ix_notifications_notification_status'))
        batch_op.drop_index(batch_op.f('ix_notifications_company_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_distributors_uuid'))
        batch_op.drop_index(batch_op.f('ix_distributors_territory_id'))
        batch_op.drop_index(batch_op.f('ix_distributors_distributor_status'))
        batch_op.drop_index(batch_op.f('ix_distributors_company_id'))

    op.drop_table('distributors')
    with op.batch_alter_table('dashboards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dashboards_uuid'))
        batch_op.drop_index(batch_op.f('ix_dashboards_user_id'))
        batch_op.drop_index(batch_op.f('ix_dashboards_dashboard_status'))
        batch_op.drop_index(batch_op.f('ix_dashboards_company_id'))

    op.drop_table('dashboards')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_uuid'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_status'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_module'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_company_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_uuid'))
        batch_op.drop_index(batch_op.f('ix_users_role_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_company_id'))
        batch_op.drop_index(batch_op.f('ix_users_account_status'))

    op.drop_table('users')
    with op.batch_alter_table('territories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_territories_uuid'))
        batch_op.drop_index(batch_op.f('ix_territories_territory_status'))
        batch_op.drop_index(batch_op.f('ix_territories_company_id'))

    op.drop_table('territories')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_uuid'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_status'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_company_id'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_permissions_uuid'))
        batch_op.drop_index(batch_op.f('ix_role_permissions_role_id'))
        batch_op.drop_index(batch_op.f('ix_role_permissions_permission_id'))

    op.drop_table('role_permissions')
    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_categories_uuid'))
        batch_op.drop_index(batch_op.f('ix_product_categories_company_id'))
        batch_op.drop_index(batch_op.f('ix_product_categories_category_status'))

    op.drop_table('product_categories')
    with op.batch_alter_table('outlet_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outlet_categories_uuid'))
        batch_op.drop_index(batch_op.f('ix_outlet_categories_company_id'))
        batch_op.drop_index(batch_op.f('ix_outlet_categories_category_status'))

    op.drop_table('outlet_categories')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_uuid'))
        batch_op.drop_index(batch_op.f('ix_roles_role_status'))
        batch_op.drop_index(batch_op.f('ix_roles_name'))

    op.drop_table('roles')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_uuid'))
        batch_op.drop_index(batch_op.f('ix_permissions_permission_status'))
        batch_op.drop_index(batch_op.f('ix_permissions_name'))
        batch_op.drop_index(batch_op.f('ix_permissions_module'))

    op.drop_table('permissions')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_uuid'))
        batch_op.drop_index(batch_op.f('ix_companies_slug'))
        batch_op.drop_index(batch_op.f('ix_companies_name'))
        batch_op.drop_index(batch_op.f('ix_companies_email'))
        batch_op.drop_index(batch_op.f('ix_companies_company_status'))
        batch_op.drop_index(batch_op.f('ix_companies_company_code'))

    op.drop_table('companies')
    # ### end Alembic commands ###
